### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by PINPAL** [CodeF53/RecipeBookMassCraft#1]
**Description**
Not working on 1.19.4:
After selecting a recipe and hitting the keybind the game crashes.

**Logs**
```
[22:03:48] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_1860.method_8110()'
	at net.F53.bookmasscraft.RecipeBookMassCraft.onClientTick(RecipeBookMassCraft.java:57) ~[recipe-book-mass-craft-1.0.0(1).jar:?]
	at fi.dy.masa.malilib.event.TickHandler.onClientTick(TickHandler.java:36) ~[malilib-fabric-1.19.4-0.15.2.jar:?]
	at net.minecraft.class_310.handler$coh000$malilib$onPostKeyboardInput(class_310.java:14515) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1958) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[22:03:48] [Server thread/INFO]: Stopping server
[22:03:48] [Server thread/INFO]: Saving players
[22:03:48] [Server thread/INFO]: Saving worlds
[22:03:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[HardcoreSeed]'/minecraft:overworld
```

**Comment by CodeF53** [comment]
I will make an update later today

**Comment by CodeF53** [comment]
Done
https://modrinth.com/mod/recipebookmasscraft/version/e2luXbPu
